import { computed } from 'vue'
import type { Table } from './useTables'

export interface Person {
  name: string
  table?: Table['id'] | null
}

export default function usePeople() {
  const people = computed<Person[]>(() => {
    return [
      { name: 'John Smith', table: null },
      { name: 'Emma Johnson', table: null },
      { name: 'Liam Brown', table: null },
      { name: 'Olivia Williams', table: null },
      { name: 'Noah Jones', table: null },
      { name: 'Ava Garcia', table: null },
      { name: 'Lucas Miller', table: null },
      { name: 'Mia Davis', table: null },
      { name: 'Ethan Rodriguez', table: null },
      { name: 'Sophia Martinez', table: null },
      { name: 'Mason Hernandez', table: null },
      { name: 'Isabella Lopez', table: null },
      { name: 'Logan Gonzalez', table: null },
      { name: 'Amelia Wilson', table: null },
      { name: 'James Anderson', table: null },
      { name: 'Harper Thomas', table: null },
      { name: 'Benjamin Taylor', table: null },
      { name: 'Evelyn Moore', table: null },
      { name: 'Elijah Jackson', table: null },
      { name: 'Abigail Martin', table: null },

      { name: 'John Smith', table: null },
      { name: 'Emma Johnson', table: null },
      { name: 'Liam Brown', table: null },
      { name: 'Olivia Williams', table: null },
      { name: 'Noah Jones', table: null },
      { name: 'Ava Garcia', table: null },
      { name: 'Lucas Miller', table: null },
      { name: 'Mia Davis', table: null },
      { name: 'Ethan Rodriguez', table: null },
      { name: 'Sophia Martinez', table: null },
      { name: 'Mason Hernandez', table: null },
      { name: 'Isabella Lopez', table: null },
      { name: 'Logan Gonzalez', table: null },
      { name: 'Amelia Wilson', table: null },
      { name: 'James Anderson', table: null },
      { name: 'Harper Thomas', table: null },
      { name: 'Benjamin Taylor', table: null },
      { name: 'Evelyn Moore', table: null },
      { name: 'Elijah Jackson', table: null },
      { name: 'Abigail Martin', table: null },

      { name: 'John Smith', table: null },
      { name: 'Emma Johnson', table: null },
      { name: 'Liam Brown', table: null },
      { name: 'Olivia Williams', table: null },
      { name: 'Noah Jones', table: null },
      { name: 'Ava Garcia', table: null },
      { name: 'Lucas Miller', table: null },
      { name: 'Mia Davis', table: null },
      { name: 'Ethan Rodriguez', table: null },
      { name: 'Sophia Martinez', table: null },
      { name: 'Mason Hernandez', table: null },
      { name: 'Isabella Lopez', table: null },
      { name: 'Logan Gonzalez', table: null },
      { name: 'Amelia Wilson', table: null },
      { name: 'James Anderson', table: null },
      { name: 'Harper Thomas', table: null },
      { name: 'Benjamin Taylor', table: null },
      { name: 'Evelyn Moore', table: null },
      { name: 'Elijah Jackson', table: null },
      { name: 'Abigail Martin', table: null },
      { name: 'John Smith', table: null },
      { name: 'Emma Johnson', table: null },
      { name: 'Liam Brown', table: null },
      { name: 'Olivia Williams', table: null },
      { name: 'Noah Jones', table: null },
      { name: 'Ava Garcia', table: null },
      { name: 'Lucas Miller', table: null },
      { name: 'Mia Davis', table: null },
      { name: 'Ethan Rodriguez', table: null },
      { name: 'Sophia Martinez', table: null },
      { name: 'Mason Hernandez', table: null },
      { name: 'Isabella Lopez', table: null },
      { name: 'Logan Gonzalez', table: null },
      { name: 'Amelia Wilson', table: null },
      { name: 'James Anderson', table: null },
      { name: 'Harper Thomas', table: null },
      { name: 'Benjamin Taylor', table: null },
      { name: 'Evelyn Moore', table: null },
      { name: 'Elijah Jackson', table: null },
      { name: 'Abigail Martin', table: null },
      { name: 'John Smith', table: null },
      { name: 'Emma Johnson', table: null },
      { name: 'Liam Brown', table: null },
      { name: 'Olivia Williams', table: null },
      { name: 'Noah Jones', table: null },
      { name: 'Ava Garcia', table: null },
      { name: 'Lucas Miller', table: null },
      { name: 'Mia Davis', table: null },
      { name: 'Ethan Rodriguez', table: null },
      { name: 'Sophia Martinez', table: null },
      { name: 'Mason Hernandez', table: null },
      { name: 'Isabella Lopez', table: null },
      { name: 'Logan Gonzalez', table: null },
      { name: 'Amelia Wilson', table: null },
      { name: 'James Anderson', table: null },
      { name: 'Harper Thomas', table: null },
      { name: 'Benjamin Taylor', table: null },
      { name: 'Evelyn Moore', table: null },
      { name: 'Elijah Jackson', table: null },
      { name: 'Abigail Martin', table: null },
      { name: 'John Smith', table: null },
      { name: 'Emma Johnson', table: null },
      { name: 'Liam Brown', table: null },
      { name: 'Olivia Williams', table: null },
      { name: 'Noah Jones', table: null },
      { name: 'Ava Garcia', table: null },
      { name: 'Lucas Miller', table: null },
      { name: 'Mia Davis', table: null },
      { name: 'Ethan Rodriguez', table: null },
      { name: 'Sophia Martinez', table: null },
      { name: 'Mason Hernandez', table: null },
      { name: 'Isabella Lopez', table: null },
      { name: 'Logan Gonzalez', table: null },
      { name: 'Amelia Wilson', table: null },
      { name: 'James Anderson', table: null },
      { name: 'Harper Thomas', table: null },
      { name: 'Benjamin Taylor', table: null },
      { name: 'Evelyn Moore', table: null },
      { name: 'Elijah Jackson', table: null },
      { name: 'Abigail Martin', table: null },
      { name: 'John Smith', table: null },
      { name: 'Emma Johnson', table: null },
      { name: 'Liam Brown', table: null },
      { name: 'Olivia Williams', table: null },
      { name: 'Noah Jones', table: null },
      { name: 'Ava Garcia', table: null },
      { name: 'Lucas Miller', table: null },
      { name: 'Mia Davis', table: null },
      { name: 'Ethan Rodriguez', table: null },
      { name: 'Sophia Martinez', table: null },
      { name: 'Mason Hernandez', table: null },
      { name: 'Isabella Lopez', table: null },
      { name: 'Logan Gonzalez', table: null },
      { name: 'Amelia Wilson', table: null },
      { name: 'James Anderson', table: null },
      { name: 'Harper Thomas', table: null },
      { name: 'Benjamin Taylor', table: null },
      { name: 'Evelyn Moore', table: null },
      { name: 'Elijah Jackson', table: null },
      { name: 'Abigail Martin', table: null },
      { name: 'John Smith', table: null },
      { name: 'Emma Johnson', table: null },
      { name: 'Liam Brown', table: null },
      { name: 'Olivia Williams', table: null },
      { name: 'Noah Jones', table: null },
      { name: 'Ava Garcia', table: null },
      { name: 'Lucas Miller', table: null },
      { name: 'Mia Davis', table: null },
      { name: 'Ethan Rodriguez', table: null },
      { name: 'Sophia Martinez', table: null },
      { name: 'Mason Hernandez', table: null },
      { name: 'Isabella Lopez', table: null },
      { name: 'Logan Gonzalez', table: null },
      { name: 'Amelia Wilson', table: null },
      { name: 'James Anderson', table: null },
      { name: 'Harper Thomas', table: null },
      { name: 'Benjamin Taylor', table: null },
      { name: 'Evelyn Moore', table: null },
      { name: 'Elijah Jackson', table: null },
      { name: 'Abigail Martin', table: null },
    ]
  })

  return { people }
}
