import { computed, ref } from 'vue'
import type { Table } from './useTables'

export interface Person {
  id: number
  name: string
}

const STORAGE_KEY = 'people'

export default function usePeople() {
  const people = ref<Person[]>(get(FAKER))

  function get<T>(fallback: T): T {
    try {
      const raw = localStorage.getItem(STORAGE_KEY)
      return raw ? JSON.parse(raw) : fallback
    } catch (e) {
      return fallback
    }
  }

  function save() {
    localStorage.setItem(STORAGE_KEY, JSON.stringify(people.value))
  }

  return { people, save }
}

const FAKER = [
  { name: 'John Smith' },
  { name: 'Emma Johnson' },
  { name: 'Liam Brown' },
  { name: 'Olivia Williams' },
  { name: 'Noah Jones' },
  { name: 'Ava Garcia' },
  { name: 'Lucas Miller' },
  { name: 'Mia Davis' },
  { name: 'Ethan Rodriguez' },
  { name: 'Sophia Martinez' },
  { name: 'Mason Hernandez' },
  { name: 'Isabella Lopez' },
  { name: 'Logan Gonzalez' },
  { name: 'Amelia Wilson' },
  { name: 'James Anderson' },
  { name: 'Harper Thomas' },
  { name: 'Benjamin Taylor' },
  { name: 'Evelyn Moore' },
  { name: 'Elijah Jackson' },
  { name: 'Abigail Martin' },
  { name: 'John Smith' },
  { name: 'Emma Johnson' },
  { name: 'Liam Brown' },
  { name: 'Olivia Williams' },
  { name: 'Noah Jones' },
  { name: 'Ava Garcia' },
  { name: 'Lucas Miller' },
  { name: 'Mia Davis' },
  { name: 'Ethan Rodriguez' },
  { name: 'Sophia Martinez' },
  { name: 'Mason Hernandez' },
  { name: 'Isabella Lopez' },
  { name: 'Logan Gonzalez' },
  { name: 'Amelia Wilson' },
  { name: 'James Anderson' },
  { name: 'Harper Thomas' },
  { name: 'Benjamin Taylor' },
  { name: 'Evelyn Moore' },
  { name: 'Elijah Jackson' },
  { name: 'Abigail Martin' },

  { name: 'John Smith' },
  { name: 'Emma Johnson' },
  { name: 'Liam Brown' },
  { name: 'Olivia Williams' },
  { name: 'Noah Jones' },
  { name: 'Ava Garcia' },
  { name: 'Lucas Miller' },
  { name: 'Mia Davis' },
  { name: 'Ethan Rodriguez' },
  { name: 'Sophia Martinez' },
  { name: 'Mason Hernandez' },
  { name: 'Isabella Lopez' },
  { name: 'Logan Gonzalez' },
  { name: 'Amelia Wilson' },
  { name: 'James Anderson' },
  { name: 'Harper Thomas' },
  { name: 'Benjamin Taylor' },
  { name: 'Evelyn Moore' },
  { name: 'Elijah Jackson' },
  { name: 'Abigail Martin' },
  { name: 'John Smith' },
  { name: 'Emma Johnson' },
  { name: 'Liam Brown' },
  { name: 'Olivia Williams' },
  { name: 'Noah Jones' },
  { name: 'Ava Garcia' },
  { name: 'Lucas Miller' },
  { name: 'Mia Davis' },
  { name: 'Ethan Rodriguez' },
  { name: 'Sophia Martinez' },
  { name: 'Mason Hernandez' },
  { name: 'Isabella Lopez' },
  { name: 'Logan Gonzalez' },
  { name: 'Amelia Wilson' },
  { name: 'James Anderson' },
  { name: 'Harper Thomas' },
  { name: 'Benjamin Taylor' },
  { name: 'Evelyn Moore' },
  { name: 'Elijah Jackson' },
  { name: 'Abigail Martin' },
  { name: 'John Smith' },
  { name: 'Emma Johnson' },
  { name: 'Liam Brown' },
  { name: 'Olivia Williams' },
  { name: 'Noah Jones' },
  { name: 'Ava Garcia' },
  { name: 'Lucas Miller' },
  { name: 'Mia Davis' },
  { name: 'Ethan Rodriguez' },
  { name: 'Sophia Martinez' },
  { name: 'Mason Hernandez' },
  { name: 'Isabella Lopez' },
  { name: 'Logan Gonzalez' },
  { name: 'Amelia Wilson' },
  { name: 'James Anderson' },
  { name: 'Harper Thomas' },
  { name: 'Benjamin Taylor' },
  { name: 'Evelyn Moore' },
  { name: 'Elijah Jackson' },
  { name: 'Abigail Martin' },
  { name: 'John Smith' },
  { name: 'Emma Johnson' },
  { name: 'Liam Brown' },
  { name: 'Olivia Williams' },
  { name: 'Noah Jones' },
  { name: 'Ava Garcia' },
  { name: 'Lucas Miller' },
  { name: 'Mia Davis' },
  { name: 'Ethan Rodriguez' },
  { name: 'Sophia Martinez' },
  { name: 'Mason Hernandez' },
  { name: 'Isabella Lopez' },
  { name: 'Logan Gonzalez' },
  { name: 'Amelia Wilson' },
  { name: 'James Anderson' },
  { name: 'Harper Thomas' },
  { name: 'Benjamin Taylor' },
  { name: 'Evelyn Moore' },
  { name: 'Elijah Jackson' },
  { name: 'Abigail Martin' },
  { name: 'John Smith' },
  { name: 'Emma Johnson' },
  { name: 'Liam Brown' },
  { name: 'Olivia Williams' },
  { name: 'Noah Jones' },
  { name: 'Ava Garcia' },
  { name: 'Lucas Miller' },
  { name: 'Mia Davis' },
  { name: 'Ethan Rodriguez' },
  { name: 'Sophia Martinez' },
  { name: 'Mason Hernandez' },
  { name: 'Isabella Lopez' },
  { name: 'Logan Gonzalez' },
  { name: 'Amelia Wilson' },
  { name: 'James Anderson' },
  { name: 'Harper Thomas' },
  { name: 'Benjamin Taylor' },
  { name: 'Evelyn Moore' },
  { name: 'Elijah Jackson' },
  { name: 'Abigail Martin' },
  { name: 'John Smith' },
  { name: 'Emma Johnson' },
  { name: 'Liam Brown' },
  { name: 'Olivia Williams' },
  { name: 'Noah Jones' },
  { name: 'Ava Garcia' },
  { name: 'Lucas Miller' },
  { name: 'Mia Davis' },
  { name: 'Ethan Rodriguez' },
  { name: 'Sophia Martinez' },
  { name: 'Mason Hernandez' },
  { name: 'Isabella Lopez' },
  { name: 'Logan Gonzalez' },
  { name: 'Amelia Wilson' },
  { name: 'James Anderson' },
  { name: 'Harper Thomas' },
  { name: 'Benjamin Taylor' },
  { name: 'Evelyn Moore' },
  { name: 'Elijah Jackson' },
  { name: 'Abigail Martin' },
].map((p, i) => ({
  ...p,
  id: i + 1,
}))
